language: go
go_import_path: github.com/nmstate/kubernetes-nmstate
go:
- "1.10"

services:
- docker

script:
- make check build
- changed_files=$(git diff --name-only $TRAVIS_COMMIT_RANGE)
- if [[ $changed_files =~ Dockerfile ]]; then
    make docker;
  fi
