required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-8.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.11"
  