apiVersion: v1
kind: Pod
metadata:
 name: state-client
 namespace: nmstate-default
spec:
  serviceAccountName: nmstate-state-controller
  containers:
  - name: state-client
    image: quay.io/nmstate/kubernetes-nmstate-state-handler:latest
    imagePullPolicy: Always
    args: ["-execution-type", "client"]
    volumeMounts:
    - name: dbus-socket
      mountPath: /run/dbus/system_bus_socket
    env:
     name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    securityContext:
      privileged: true
  volumes:
  - name: dbus-socket
    hostPath:
      path: /run/dbus/system_bus_socket
      type: Socket
