apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: state-controller
  namespace: nmstate-default
spec:
  template:
    metadata:
      labels:
        nmstate.io: state-controller
    spec:
      serviceAccountName: nmstate-state-controller
      containers:
        - name: state-controller
          image: quay.io/nmstate/kubernetes-nmstate-state-handler:latest
          imagePullPolicy: Always
          args: ["-execution-type", "controller"]
          volumeMounts:
          - name: dbus-socket
            mountPath: /run/dbus/system_bus_socket
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          securityContext:
            privileged: true
      volumes:
      - name: dbus-socket
        hostPath:
          path: /run/dbus/system_bus_socket
          type: Socket
