apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: state-controller
  namespace: nmstate-default
spec:
  template:
    metadata:
      labels:
        nmstate.io: state-controller
    spec:
      serviceAccountName: nmstate-state-controller
      containers:
        - name: state-controller
          image: yuvalif/k8s-node-network-state-controller
          args: ["-type", "state"]
          volumeMounts:
          - name: dbus-socket
            mountPath: /run/dbus/system_bus_socket
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      volumes:
      - name: dbus-socket
        hostPath:
          path: /run/dbus/system_bus_socket
          type: Socket
