apiVersion: nmstate.io/v1
kind: NodeNetworkState
metadata:
  creationTimestamp: null
  name: node1-network-state
spec:
  desiredState:
    interfaces:
    - description: Production Network
      ethernet:
        auto-negotiation: true
        duplex: full
        speed: 1000
      ipv4:
        address:
        - ip: 10.0.0.2
          prefix-length: 24
        dhcp: true
        enabled: true
        neighbors:
        - ip: 10.0.0.1
          linkLayerAddress: 00:25:96:FF:FE:12:34:56
      ipv6:
        address:
        - ip: 2001:db8::1:1
          prefix-length: 64
        dhcp: false
        enabled: true
      mtu: 1400
      name: eth0
      state: up
      type: ethernet
    - description: Production Network
      ethernet:
        auto-negotiation: false
        duplex: full
        speed: 0
      ipv4:
        dhcp: true
        enabled: true
      ipv6:
        dhcp: true
        enabled: true
      mtu: 1400
      name: eth1
      state: up
      type: ethernet
    - description: Deprecated Bridge
      name: old-br
      state: down
      type: ovs-bridge
    - description: Another Deprecated Bridge
      name: dummy0
      state: absent
      type: dummy
  managed: true
  nodeName: node1
status:
  currentState:
    capabilities: null
    interfaces: null

