apiVersion: nmstate.io/v1
kind: NodeNetworkState
metadata:
  creationTimestamp: null
  name: node1-network-state
spec:
  desiredState:
    interfaces:
    - name: eth0
      state: up
      type: ethernet
    - name: foo0
      state: down
      type: unknown
    - name: dummy0
      state: absent
      type: dummy
    - mtu: 1400
      name: dummy1
      state: up
      type: dummy
  managed: true
  nodeName: node1
status:
  currentState:
    capabilities: null
    interfaces: null

