apiVersion: nmstate.io/v1
kind: NodeNetConfPolicy
metadata:
  creationTimestamp: null
  name: my-node-net-conf-policy
spec:
  autoconfig: null
  desiredState: null
  match:
    items: null
    metadata: {}

